/**
 * Contact.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {
    tableName: 'Contact',
    meta: {
        schemaName: 'sfdc'
    },
    // identity: 'account',
    autoPK: false,
    autoCreatedAt: 'CreatedDate',
    autoUpdatedAt: 'LastModifiedDate',
    attributes: {
        // AccountId: 'string',
        // FirstName: 'string',
        // MiddleName: 'string',
        // LastName: 'string',
        // Name: 'string',
        // RecordTypeId: 'string',
        // Phone: 'string',
        // MobilePhone: 'string',
        // Email: 'string',
        // Title: 'string',
        // Department: 'string',
        // StatusPerson__c: 'string',
        // uid__c: 'string',
        // Activated__c: 'datetime',
        // LastLoginPerson__c: 'datetime',
        // // DOB__c: 'date',
        // Timezone__c: 'string',
        // // MemberName__c: 'string',
        // MemberId__c: 'string',
        // // PrefStartAnimation__c: 'string',
        // // PrefStartSound__c: 'string',
        // MailingStreet: 'string',
        // MailingCity: 'string',
        // MailingState: 'string',
        // MailingPostalCode: 'string',
        // MailingCountry: 'string',
        // IsPersonAccount: {
        //     type: 'boolean',
        //     defaultsTo: true
        // },
        // OwnerId: {
        //     type: 'string',
        //     defaultsTo: ''
        // },
        // CreatedById: {
        //     type: 'string',
        //     defaultsTo: ''
        // },
        // LastModifiedById: {
        //     type: 'string',
        //     defaultsTo: ''
        // },
        // IsDeleted: {
        //     type: 'boolean',
        //     // defaultsTo: false
        // },
        // IsEmailBounced: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // No_Show_CP__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // LinkedIn_Connected__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // Zendesk__Create_in_Zendesk__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // Zendesk__isCreatedUpdatedFlag__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // Zendesk__Zendesk_OutofSync__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        // Kids__c: {
        //     type: 'boolean',
        //     defaultsTo: false
        // },
        //
        // SystemModstamp: 'datetime',
        // AboutMeBioPerson__c: 'string',
        // AboutMeURLPerson__c: 'string',
        // AboutMeUsernamePerson__c: 'string',
        // AngelListBioPerson__c: 'string',
        // AngelListFollowersPerson__c: 'string',
        // AngelListURLPerson__c: 'string',
        // AngelListUsernamePerson__c: 'string',
        // AnnualIncome__c: 'string',
        // AnonymousId__c: 'string',
        // CompSum__c: 'string',
        // County__c: 'string',
        // CreatedDate: 'string',
        // CRT__c: 'string',
        // CurrencyIsoCode: 'string',
        // EarnSum__c: 'string',
        // Education__c: 'string',
        // EmailBouncedDate: 'string',
        // EmailBouncedReason: 'string',
        // EmailFour__c: 'string',
        // EmailThree__c: 'string',
        // EmailTwo__c: 'string',
        // EndToToday__c: 'float',
        // ExtensionDays__c: 'float',
        // Extensions__c: 'float',
        // FacebookId__c: 'string',
        // FacebookURLPerson__c: 'string',
        // Fax: 'string',
        // FullContactUpdated__c: 'string',
        // Gender__c: 'string',
        // GitHubURLPerson__c: 'string',
        // GitHubUsernamePerson__c: 'string',
        // GooglePlusBioPerson__c: 'string',
        // GooglePlusFollowersPerson__c: 'string',
        // GooglePlusURLPerson__c: 'string',
        // GooglePlusUsernamePerson__c: 'string',
        // GravatarURLPerson__c: 'string',
        // gTalk__c: 'string',
        // Id: 'string',
        // imgurl__c: 'string',
        // InstagramBioPerson__c: 'string',
        // InstagramFollowersPerson__c: 'string',
        // InstagramURLPerson__c: 'string',
        // InstagramUsernamePerson__c: 'string',
        // Jigsaw: 'string',
        // JigsawContactId: 'string',
        // KloutPerson__c: 'string',
        // LastActivityDate: 'date',
        // LastCURequestDate: 'datetime',
        // LastCUUpdateDate: 'datetime',
        // LastModifiedDate: 'datetime',
        // LastReferencedDate: 'datetime',
        // LastUpdatedPerson__c: 'datetime',
        // LastViewedDate: 'datetime',
        // LID__LinkedIn_Company_Id__c: 'string',
        // LID__LinkedIn_Member_Token__c: 'string',
        // LinkedInBioPerson__c: 'string',
        // LinkedInFollowersPerson__c: 'float',
        // LinkedInURLPerson__c: 'string',
        // LinkedInUsernamePerson__c: 'string',
        // Login__c: 'string',
        // MailingAddress: 'string',
        // MailingGeocodeAccuracy: 'string',
        // MailingLatitude: 'float',
        // MailingLongitude: 'float',





        IsDeleted : "boolean",
        MasterRecordId : "string",
        AccountId : "string",
        IsPersonAccount : "boolean",
        LastName : "string",
        FirstName : "string",
        Salutation : "string",
        MiddleName : "string",
        Suffix : "string",
        Name : "string",
        RecordTypeId : "string",
        MailingStreet : "string",
        MailingCity : "string",
        MailingState : "string",
        MailingPostalCode : "string",
        MailingCountry : "string",
        MailingLatitude : "float",
        MailingLongitude : "float",
        MailingGeocodeAccuracy : "string",
        MailingAddress : "string",
        Phone : "string",
        Fax : "string",
        MobilePhone : "string",
        ReportsToId : "string",
        Email : "string",
        Title : "string",
        Department : "string",
        CurrencyIsoCode : "string",
        OwnerId : "string",
        CreatedDate : "datetime",
        CreatedById : "string",
        LastModifiedDate : "datetime",
        LastModifiedById : "string",
        SystemModstamp : "datetime",
        LastActivityDate : "date",
        LastCURequestDate : "datetime",
        LastCUUpdateDate : "datetime",
        LastViewedDate : "datetime",
        LastReferencedDate : "datetime",
        EmailBouncedReason : "string",
        EmailBouncedDate : "datetime",
        IsEmailBounced : "boolean",
        PhotoUrl : "string",
        Jigsaw : "string",
        JigsawContactId : "string",
        YelpURLPerson__c : "string",
        YelpNicknamePerson__c : "string",
        YelpFollowersPerson__c : "float",
        YelpBioPerson__c : "string",
        imgurl__c : "string",
        Salespeople__c : "string",
        ZendeskId__c : "string",
        CRT__c : "string",
        AnonymousId__c : "string",
        Meeting_Type_CP__c : "string",
        No_Show_CP__c : "boolean",
        LID__LinkedIn_Company_Id__c : "string",
        LID__LinkedIn_Member_Token__c : "string",
        AboutMeURLPerson__c : "string",
        AboutMeBioPerson__c : "string",
        AboutMeUsernamePerson__c : "string",
        AngelListBioPerson__c : "string",
        AngelListURLPerson__c : "string",
        AngelListUsernamePerson__c : "string",
        FacebookURLPerson__c : "string",
        GitHubURLPerson__c : "string",
        GitHubUsernamePerson__c : "string",
        GooglePlusURLPerson__c : "string",
        GooglePlusUsernamePerson__c : "string",
        GooglePlusFollowersPerson__c : "float",
        InstagramBioPerson__c : "string",
        InstagramURLPerson__c : "string",
        InstagramUsernamePerson__c : "string",
        InstagramFollowersPerson__c : "float",
        LinkedInBioPerson__c : "string",
        LinkedInURLPerson__c : "string",
        LinkedInUsernamePerson__c : "string",
        LinkedInFollowersPerson__c : "float",
        PinterestURLPerson__c : "string",
        PinterestUsernamePerson__c : "string",
        PinterestFollowersPerson__c : "float",
        QuoraURLPerson__c : "string",
        QuoraBioPerson__c : "string",
        QuoraFollowersPerson__c : "float",
        YouTubeURLPerson__c : "string",
        YouTubeUsernamePerson__c : "string",
        YouTubeFollowersPerson__c : "float",
        TwitterBioPerson__c : "string",
        TwitterURLPerson__c : "string",
        TwitterUsernamePerson__c : "string",
        TwitterFollowersPerson__c : "float",
        KloutPerson__c : "float",
        Skype__c : "string",
        gTalk__c : "string",
        GravatarURLPerson__c : "string",
        Outreach__c : "string",
        Persona__c : "string",
        County__c : "string",
        StateCode__c : "string",
        EmailTwo__c : "string",
        EmailThree__c : "string",
        EmailFour__c : "string",
        AngelListFollowersPerson__c : "float",
        GooglePlusBioPerson__c : "string",
        LinkedIn_Connected__c : "boolean",
        PinterestBioPerson__c : "string",
        YouTubeBioPerson__c : "string",
        Passcode__c : "string",
        Zendesk__Create_in_Zendesk__c : "boolean",
        Zendesk__Last_Sync_Date__c : "datetime",
        Zendesk__Last_Sync_Status__c : "string",
        Zendesk__Result__c : "string",
        Zendesk__Tags__c : "string",
        Zendesk__Zendesk_OutofSync__c : "boolean",
        Zendesk__Zendesk_oldTags__c : "string",
        Zendesk__isCreatedUpdatedFlag__c : "boolean",
        Zendesk__notes__c : "string",
        Zendesk__zendesk_id__c : "string",
        MemberId__c : "string",
        MembershipStart__c : "date",
        ExtensionDays__c : "float",
        Extensions__c : "float",
        CompSum__c : "float",
        PaidSum__c : "float",
        EarnSum__c : "float",
        MembershipEnd__c : "date",
        EndToToday__c : "float",
        StatusPerson__c : "string",
        uid__c : "string",
        Activated__c : "datetime",
        statusChanged__c : "datetime",
        LastLoginPerson__c : "datetime",
        LastUpdatedPerson__c : "datetime",
        PasswordChanged__c : "datetime",
        TransitioningToStatus__c : "string",
        Login__c : "string",
        PartnerId__c : "string",
        StatusPersonCopy__c : "string",
        FacebookId__c : "string",
        Timezone__c : "string",
        Gender__c : "string",
        StatusMarital__c : "string",
        AnnualIncome__c : "string",
        Education__c : "string",
        StatusEmployment__c : "string",
        Kids__c : "boolean",
        StoreOne__c : "string",
        StoreTwo__c : "string",
        StoreThree__c : "string",
        StoreFour__c : "string",
        StoreFive__c : "string",
        FullContactUpdated__c : "datetime",
        Id : "integer"

    }
};